# coding: utf-8

"""
    Segment Public API

    The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API. 

    The version of the OpenAPI document: 73.0.1
    Contact: friends@segment.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from segment_public_api.models.audience_definition import AudienceDefinition
from segment_public_api.models.audience_preview_result import AudiencePreviewResult
from segment_public_api.models.audience_size import AudienceSize
from segment_public_api.models.read_audience_preview_options import ReadAudiencePreviewOptions
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AudiencePreview(BaseModel):
    """
    An audience preview.
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier for tracking and retrieving results of an audience preview.")
    audience_type: StrictStr = Field(description="The audience type of the preview.  Possible values: USERS, ACCOUNTS, LINKED.", alias="audienceType")
    definition: AudienceDefinition = Field(description="Definition that was used to calculate the audience preview.")
    options: ReadAudiencePreviewOptions = Field(description="Options that were used to calculate the audience preview.")
    status: StrictStr = Field(description="Status for the audience preview.")
    results: Optional[List[AudiencePreviewResult]] = Field(default=None, description="Sampled result membership for the audience preview. Only has a value if the status is 'COMPLETED'.")
    size: Optional[AudienceSize] = Field(default=None, description="Result membership size for the audience preview. Only has a value if status is 'COMPLETED'.")
    failure_reason: Optional[StrictStr] = Field(default=None, description="Explanation of why the audience preview failed. Only has a value if status is 'FAILED'.", alias="failureReason")
    __properties: ClassVar[List[str]] = ["id", "audienceType", "definition", "options", "status", "results", "size", "failureReason"]

    @field_validator('audience_type')
    def audience_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ACCOUNTS', 'LINKED', 'USERS']):
            raise ValueError("must be one of enum values ('ACCOUNTS', 'LINKED', 'USERS')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['COMPLETED', 'FAILED', 'RUNNING']):
            raise ValueError("must be one of enum values ('COMPLETED', 'FAILED', 'RUNNING')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AudiencePreview from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of definition
        if self.definition:
            _dict['definition'] = self.definition.to_dict()
        # override the default output from pydantic by calling `to_dict()` of options
        if self.options:
            _dict['options'] = self.options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in results (list)
        _items = []
        if self.results:
            for _item_results in self.results:
                if _item_results:
                    _items.append(_item_results.to_dict())
            _dict['results'] = _items
        # override the default output from pydantic by calling `to_dict()` of size
        if self.size:
            _dict['size'] = self.size.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AudiencePreview from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "audienceType": obj.get("audienceType"),
            "definition": AudienceDefinition.from_dict(obj["definition"]) if obj.get("definition") is not None else None,
            "options": ReadAudiencePreviewOptions.from_dict(obj["options"]) if obj.get("options") is not None else None,
            "status": obj.get("status"),
            "results": [AudiencePreviewResult.from_dict(_item) for _item in obj["results"]] if obj.get("results") is not None else None,
            "size": AudienceSize.from_dict(obj["size"]) if obj.get("size") is not None else None,
            "failureReason": obj.get("failureReason")
        })
        return _obj


