# coding: utf-8

"""
    Segment Public API

    The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API. 

    The version of the OpenAPI document: 67.0.0
    Contact: friends@segment.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool

class DestinationMetadataPlatformsV1(BaseModel):
    """
    Represents platforms that a given Destination supports.  # noqa: E501
    """
    browser: Optional[StrictBool] = Field(None, description="Whether this Destination supports browser events.")
    server: Optional[StrictBool] = Field(None, description="Whether this Destination supports server events.")
    mobile: Optional[StrictBool] = Field(None, description="Whether this Destination supports mobile events.")
    warehouse: Optional[StrictBool] = Field(None, description="Whether this Destination supports Warehouse events.")
    cloud_app_object: Optional[StrictBool] = Field(None, alias="cloudAppObject", description="Whether this Destination supports cloud app object events.")
    linked_audiences: Optional[StrictBool] = Field(None, alias="linkedAudiences", description="Whether this Destination supports linked audiences.")
    __properties = ["browser", "server", "mobile", "warehouse", "cloudAppObject", "linkedAudiences"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DestinationMetadataPlatformsV1:
        """Create an instance of DestinationMetadataPlatformsV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DestinationMetadataPlatformsV1:
        """Create an instance of DestinationMetadataPlatformsV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DestinationMetadataPlatformsV1.parse_obj(obj)

        _obj = DestinationMetadataPlatformsV1.parse_obj({
            "browser": obj.get("browser"),
            "server": obj.get("server"),
            "mobile": obj.get("mobile"),
            "warehouse": obj.get("warehouse"),
            "cloud_app_object": obj.get("cloudAppObject"),
            "linked_audiences": obj.get("linkedAudiences")
        })
        return _obj


