# coding: utf-8

"""
    Segment Public API

    The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API. 

    The version of the OpenAPI document: 65.0.0
    Contact: friends@segment.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr

class LivePluginsAlpha(BaseModel):
    """
    Represents a Live Plugin bundle.  # noqa: E501
    """
    id: StrictStr = Field(..., description="The Live Plugin id.")
    source_id: StrictStr = Field(..., alias="sourceId", description="The Source id.")
    created_at: StrictStr = Field(..., alias="createdAt", description="Creation date.")
    created_by: StrictStr = Field(..., alias="createdBy", description="Creating user's id.")
    download_url: StrictStr = Field(..., alias="downloadURL", description="The CDN URL that can be used to fetch your latest Live Plugin bundle.")
    version: Union[StrictFloat, StrictInt] = Field(..., description="Revision number associated with the latest Live Plugin.")
    code: Optional[StrictStr] = Field(None, description="The code of the Live Plugin.")
    __properties = ["id", "sourceId", "createdAt", "createdBy", "downloadURL", "version", "code"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LivePluginsAlpha:
        """Create an instance of LivePluginsAlpha from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if code (nullable) is None
        # and __fields_set__ contains the field
        if self.code is None and "code" in self.__fields_set__:
            _dict['code'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LivePluginsAlpha:
        """Create an instance of LivePluginsAlpha from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LivePluginsAlpha.parse_obj(obj)

        _obj = LivePluginsAlpha.parse_obj({
            "id": obj.get("id"),
            "source_id": obj.get("sourceId"),
            "created_at": obj.get("createdAt"),
            "created_by": obj.get("createdBy"),
            "download_url": obj.get("downloadURL"),
            "version": obj.get("version"),
            "code": obj.get("code")
        })
        return _obj


