# coding: utf-8

"""
    Segment Public API

    The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API. 

    The version of the OpenAPI document: 58.1.1
    Contact: friends@segment.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field
from segment_public_api.models.analytics import Analytics
from segment_public_api.models.key import Key

class StepLevelAnalytics(BaseModel):
    """
    StepLevelAnalytics
    """
    var_from: Optional[Key] = Field(None, alias="from")
    to: Key = Field(...)
    analytics: Analytics = Field(...)
    __properties = ["from", "to", "analytics"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StepLevelAnalytics:
        """Create an instance of StepLevelAnalytics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of var_from
        if self.var_from:
            _dict['from'] = self.var_from.to_dict()
        # override the default output from pydantic by calling `to_dict()` of to
        if self.to:
            _dict['to'] = self.to.to_dict()
        # override the default output from pydantic by calling `to_dict()` of analytics
        if self.analytics:
            _dict['analytics'] = self.analytics.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StepLevelAnalytics:
        """Create an instance of StepLevelAnalytics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StepLevelAnalytics.parse_obj(obj)

        _obj = StepLevelAnalytics.parse_obj({
            "var_from": Key.from_dict(obj.get("from")) if obj.get("from") is not None else None,
            "to": Key.from_dict(obj.get("to")) if obj.get("to") is not None else None,
            "analytics": Analytics.from_dict(obj.get("analytics")) if obj.get("analytics") is not None else None
        })
        return _obj


